name: update lastupdate

on:
  push:
    branches:
      - development
    paths:
      - data/*

jobs:
  update:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Commit files
        run: |
          D=$(TZ=Asia/Tokyo date '+%Y-%m-%d %H:%M') && sed -i data/data.json -e "s/\"lastUpdate\"\:.*/\"lastUpdate\"\:\ \"${D//-/\\\/}\",/"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/data.json
          git commit -m "Updates datetime of last update."
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: development
          force: true
